name: String Functions
on:
    workflow_dispatch:
jobs:
    string-functions:
        runs-on: ubuntu-latest    
        steps:
        - name: contains()    
          run: |
            echo "=========================================="  
            echo " contains() "
            echo "=========================================="
            echo "ref contains main: ${{ contains(github.ref, 'main') }}"
            echo " repo contains Action: ${{ contains( github.repository, 'Action') }}"
            echo "actor contains: ${{ contains( github.actor, 'bhanu') }}"
        - name: startsWith()
          if: startsWith( github.action_repository, 'C')
          run: 
            echo "=========================================="  
            echo " starts with ch "            
     
